name: JordanWollman
favicon: null
layout_spectrum: 0.09414151147939265
typography_spectrum: 0.14308527717366815
title: Jordan Wollman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5575233816634864
  lightness: 0.42699152836576104
  saturation: 0.48331253230571747
  rhythmicContrast: 0.5857550203800201
purpose: []
