typography_spectrum: 0.20920188259333372
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9359677385073155
  lightness: 0.3958345144055784
  saturation: 0.040799414506182075
  rhythmicContrast: 0.49388678348623216
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34915434499271214
analytics:
  google: null
  facebook: null
  twitter: null
name: JordanWollman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Thoughts: on Medium.com'
    url: 'http://medium.com/@jordanwollman'
    type: external
favicon: null
title: Jordan Wollman
description: Brand Strategist Extraordinaire
purpose: []
