typography_spectrum: 0.24744
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: JordanWollman
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Jordan Wollman
description: Brand Strategist Extraordinaire
purpose: []
